---
title: 'Rename SimU IDs'
output: html_notebook
---


```{r}
library(sf)
library(GISTools)
library(rgdal)
require(ggplot2)
library(dplyr)
```

## Read
```{r}
simU_dir <- "C:\\Users\\Grace\\Documents\\FABLE\\GLOBIOM\\SimU\\gis\\"
simU_fn <- "SimU_all_select840_USstateSplit_proj.shp"
simU <- st_read(simU_fp)
```

```{r}
ggplot() + 
  geom_sf(data = simU, size = 3, color = "black", fill = "cyan1") + 
  ggtitle("SimUs") + 
  coord_sf()
```


## update names
```{r}
## Get FID_SimU_a duplicates that need new names (i.e., get list of FID_SimU_a that occur more than once)
count <- as.data.frame(table(simU$FID_SimU_a))
count_df <- subset(count, Freq >1)

simU_wFreq<- merge(simU, count, by.x = "FID_SimU_a", by.y = "Var1")

simU_wFreq$SimUIDn <- NULL

for(FID in count_df$Var1){
  #print(FID)
  ## retrieve the SimU corresponding to the FID
  simuid_val <- simU_wFreq[simU_wFreq$FID_SimU_a == FID, ]$SimUID
  
  ## get frequency
  freq <- count_df[count_df$Var1 == FID,]$Freq
  
  ## create vector with new names
  SimUID_new_vector <- paste(simuid_val, seq(1, freq), sep= "_")
  
  ## Assign the new SimUIDs
  simU_wFreq$SimUIDn[simU_wFreq$FID_SimU_a == FID] <- SimUID_new_vector
}

## Assign the rest of the rows to the original simUID
simU_wFreq <- simU_wFreq %>% mutate(SimUIDn = ifelse(is.na(SimUIDn), SimUID, SimUIDn))

### code that didn't work, but may still be useful for later:
#test <- simU %>% 
#  arrange(FID_SimU_a) %>% 
#  group_by(FID_SimU_a) %>% 
#  mutate(SimUID_new = ifelse(FID_SimU_a %in% count_df$Var1, paste0(SimUID, "_", ), SimUID)
         
#newSimUids <- with(simU_wFreq, ave(as.character(simU_wFreq$SimUID), simU_wFreq$FID_SimU_a, FUN=function(x) make.unique(x,sep="_")))
#simU_wFreq$SimUID_state <- newSimUids

## Write new output shapefile
st_write(simU_wFreq, paste(simU_dir, paste(gsub(".shp", "", simU_fn), "newSUcol.shp", sep="_"), sep=""))

#simU_wFreq_spdf <- as(simU_wFreq, 'Spatial')
#writeOGR(obj=simU_wFreq_spdf, dsn=simU_dir, layer= paste(gsub(".shp", "", simU_fn), "newSUcol.shp", sep="_"), driver="ESRI Shapefile")
```

